gos_web_socket:
    server:
        host: %app_host%
        port: %app_port%
        router:
            resources:
                - "@AppBundle/Resources/config/pubsub_routing.yml"

    client:
        firewall: main
        session_handler: @session.handler.pdo
